### ISSUE TITLE
semPaths default args generate warnings from qgraph

### ISSUE THREAD

**Issue by machow** [SachaEpskamp/semPlot#10]
I suspect that originally args from semPaths were harmlessly being passed through to qgraph, but a commit back in February added a warning for unused args. (I'm using the master branch of semPlot).

This is the qgraph commit where the warning was introduced:

https://github.com/SachaEpskamp/qgraph/commit/3ff75af3070c38baa07490a4d82399faac591226

**Comment by SachaEpskamp** [comment]
This should be fixed in devel versions. There are some hidden qgraph arguments used by semPlot ;)
