### ISSUE TITLE
Error using models from piecewiseSEM

### ISSUE THREAD

**Issue by JackieRaw33** [SachaEpskamp/semPlot#16]
I receive an error when trying to run semPaths using models from a SEM built using piecewise SEM

> SEMplot2<-semPaths(M2 + M4 + M6 + M7 + M9 + M10, what = "std", layout="spring",  "std", intercepts=FALSE)
Error in eval(family$initialize) : y values must be 0 <= y <= 1

The models are in various forms, including lm, glm, and gls. I suspect the issue is with one of the glm models that are using the binomial or quasipoisson family. Is there a way to plot this SEM?

Thanks

**Comment by SachaEpskamp** [comment]
HI Jackie, What is piecewise SEM? It is likely not supported at the moment.

Best, Sacha
