### ISSUE TITLE
Change some imports to suggests

### ISSUE THREAD

**Issue by cddesja** [SachaEpskamp/semPlot#18]
Installing semPlot results in the following:

```r
> install.packages("semPlot")
also installing the dependencies ‘checkmate’, ‘htmlwidgets’, ‘coda’,
‘Formula’, ‘latticeExtra’, ‘acepack’, ‘htmlTable’, ‘viridis’, 
‘statnet.common’, ‘network’, ‘rjson’, ‘arm’, ‘RUnit’, ‘mvtnorm’, 
‘ellipse’, ‘Hmisc’, ‘jpeg’, ‘png’, ‘sna’, ‘glasso’, ‘huge’, ‘fdrtool’, 
‘d3Network’, ‘ggm’, ‘gtools’, ‘BDgraph’, ‘pbapply’, ‘matrixcalc’, 
‘mi’, ‘kutils’, ‘StanHeaders’, ‘rpf’, ‘qgraph’, ‘sem’, ‘XML’, ‘igraph’, 
‘lisrelToR’, ‘rockchalk’, ‘corpcor’, ‘OpenMx’
```

This seems like an extremely long list of dependencies. If I look at the Suggests and Imports from the Description file I find the following:

```r
Suggests: MplusAutomation (>= 0.5-3)
Imports:  qgraph (>= 1.2.4), lavaan (>= 0.5-11), sem (>= 3.1-0), plyr, XML, igraph (>= 0.6-3), lisrelToR, rockchalk, colorspace, corpcor, methods, semTools, OpenMx
```

Why depend on `lavaan`, `sem`, `lisrelToR`, `semTools`, and `OpenMx`? Why not just suggest these and import just one? A user of this package would only end up using one or two of these packages and `semTools` is essentially an add-on package. 

Depending on this many packages means that the end-user could end up with broken functions because of API changes and incompatible packages.

**Comment by SachaEpskamp** [comment]
Functions from these packages are used in the code, hence I chose to import these. I generally do not like building require calls into the code itself and prefer to use imports. But this might be something worth considering indeed.
