### ISSUE TITLE
How about output it into visio(Microsoft)？

### ISSUE THREAD

**Issue by wanglu2014** [SachaEpskamp/semPlot#24]
openMX can output dot file, can semPlot transform lavaan model into dot file?

**Comment by SachaEpskamp** [comment]
This is not supported yet. All that's needed is to write a function that takes a semPlotModel and translate it to a dot file, in which case all supported packages (like lavaan) are automatically supported too. But this is not on my immediate to do list...

**Comment by wanglu2014** [comment]
Understand, there are so many sciences to discovery. Thank for your timely reply~
