### ISSUE TITLE
"Error in `*tmp*`[[i]] : subscript out of bounds" in `semPlotModel()`

### ISSUE THREAD

**Issue by DaniMori** [SachaEpskamp/semPlot#30]
This error seems to happen every time `semPlotModel()` is called with a `lavaan` object, at least on R 4.0.2.

I'm afraid it has to do with the method dispatcher for the class `lavaan`, which makes it almost impossible to track down the error. I wonder if it is related to the major changes in the R internals in version 4.

I leave a reprex below:

``` r
library(psych, quietly = TRUE)
library(lavaan, quietly = TRUE)
library(semPlot, quietly = TRUE)

data("Thurstone")

th_model <- "g =~ Sentences + Vocabulary + Sent.Completion + First.Letters"

th_fit <- cfa(th_model, sample.cov = Thurstone, sample.nobs = 213)

semPaths(th_fit)
#> Error in `*tmp*`[[i]]: subscript out of bounds
```

<sup>Created on 2020-07-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DaniMori** [comment]
It seems like installing the dev version from github solves it...

**Comment by DaniMori** [comment]
It seems like installing the dev version from github solves it...

**Comment by SachaEpskamp** [comment]
Thanks! I'll submit it to CRAN!
