### ISSUE TITLE
Single indicators

### ISSUE THREAD

**Issue by HanZhang-psych** [SachaEpskamp/semPlot#32]
Hello!

I wonder if there is a way to selectively show a single indicator in the structural part of the model while hiding the measurement part. Here is an example:

```
library(lavaan)
library(semPlot)
model <- "
  lv1 =~ mpg + cyl + wt
  lv2 =~ am + vs + gear
  drat ~ lv1
  lv2 ~ drat
  
"
fit <- sem(model, data = mtcars)
semPaths(fit)
```
![image](https://user-images.githubusercontent.com/17090544/103374975-e01dad80-4aa6-11eb-9598-0254b60b77dd.png)

I'd like to hide the manifest variables but keep `drat` in the plot. Using `structural=T` would remove `drat` from the plot.

![image](https://user-images.githubusercontent.com/17090544/103374987-ea3fac00-4aa6-11eb-9406-9468e969201d.png)

Thank you!
Han

**Comment by SachaEpskamp** [comment]
Hi Han,

This is not possible at the moment, but you could represent DRT with a latent variable in the lavaan model for an equivalent setup.

Best, Sacha
