### ISSUE TITLE
std.lv standardization

### ISSUE THREAD

**Issue by dpmoriarity** [SachaEpskamp/semPlot#33]
Hi Sacha,

Sorry if this isn't the correct place to post this, it's not really an issue or bug.

Is there anyway to make the semPaths loadings match "std.lv" loadings? When I set the semPaths to model "std" it matches the output for "standardizedSolution(model)" output but I want it to match "standardizedSolution(model, type="std.lv") output.

**Comment by SachaEpskamp** [comment]
No this is not implemented at the moment..
