### ISSUE TITLE
Array dimension error in semPaths

### ISSUE THREAD

**Issue by pamlacher** [SachaEpskamp/semPlot#39]
I tried to plot a two level lavaan SEM and got this error message:

> Fehler in dimnames(x) <- dn : 
>   Länge von 'dimnames' [2] ungleich der Arrayausdehnung

This is the code for the lavaan model (sorry for the odd formatting, github seems to get confused by something):

> lavmodeldef <- '
>               level: 1
>                 Post ~ Pre_z + SR3.theta + math.fscores + SK.theta + SW2.theta
> 
>               level: 2
>                 Post ~ Pre_z + math.fscores
> '
> lavmodel <- sem(model = lavmodeldef, data = dta.klasse, cluster = "Lehrperson", estimator="MLR")
> 
> 

Thanks for help or fixing!

**Comment by SachaEpskamp** [comment]
Multi level lavaan models are not supported, sorry.
