### ISSUE TITLE
Numbers on top of each other + invisible lines + more documentation/examples for custom layout

### ISSUE THREAD

**Issue by Deleetdk** [SachaEpskamp/semPlot#4]
Great work on this package! :)

My problem is that the path coefs overlap so they are not readable. Consider this bi-factor model.

![overlap_numbers](https://cloud.githubusercontent.com/assets/6759913/9020544/bda355de-37d8-11e5-9d2f-fcdb13d87417.png)

To get around this issue, I tried using custom layouts. There is not a lot of documentation on this and only a single example with no code and no figure. http://sachaepskamp.com/documentation/qgraph/ ("Specifying the layout").

However, I got it to work, except that lines in the center of the plot become invisible.

![bi-factor](https://cloud.githubusercontent.com/assets/6759913/9020551/2846a5c6-37d9-11e5-9279-3f1893c2e2f4.png)

Still, the numbers are visible and it is not a large problem for understanding, as the lines can be inferred from the arrow heads.

Am I missing something?

**Comment by SachaEpskamp** [comment]
Hi Deleetdk,

You can also use the bifactor argument in semPaths:

semPaths(..., bifactor = "g")

Should do the same trick. To get numbers on different positions on the edge you can use the "edge.label.position" argument in semPaths which can be used to prevent labels getting on top of eachother.

As for the invisible edge, I have no idea how that happens... Do you have a reproducible code? If the model is done in lavaan then just the lavaan model syntax should be good as well.

**Comment by Deleetdk** [comment]
The code is part of a Shiny app I am working on. I have uploaded the current version here: https://github.com/Deleetdk/Jensens_method_2

It is not ready for public release, but the SEM bi-factor plot is working with user input from a table.

The lavaan syntax:

```
g =~ I1 + I2 + I3 + I4 + I5 + I6 + I7 + I8 + I9
F1 =~ I1 + I2 + I3
F2 =~ I4 + I5 + I6
F3 =~ I7 + I8 + I9
```

Manual semPlot syntax:

```
> m = matrix(nrow = 3, ncol = 9)
> m[1, ] = c(0, 11, 0, 0, 12, 0, 0, 13, 0)
> m[2, ] = 1:9
> m[3, ] = c(rep(0, 4), 10, rep(0, 4))
> m
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
 [1,]    0   11    0    0   12    0    0   13    0
 [2,]    1    2    3    4    5    6    7    8    9
 [3,]    0    0    0    0   10    0    0    0    0
```

semPlot call:

```
semPaths(fit, whatLabels = "std",  #what numbers to show
         residuals = F,            #dont show resids
         curve = 1.5,              #curve cor between latents
         fixedStyle = "white",     #make LV cor invis
         layout = m                #manual layout
)
```

However, I am looking to make this layout automatic, so I would rather find some way to make the semPlot get it right. Otherwise, I have to generate these semPlot layout matrices also, which I do think is doable.

The app is part of my series of Shiny apps to teach statistics. It is a more advanced version of this prior app about Jensen's method. http://emilkirkegaard.dk/understanding_statistics/?app=Jensens_method

If you are familiar with psychometrics or differential psychology, it is also called method of correlated vectors (I think this is a bad name, so I have renamed it in honor of its inventor). Basically, I am building a simulator that lets user specify the factor loadings, number of group factors and number of subtests. From this, the simulator will generate data and analyze the data with various methods commonly used to use Jensen's method.

I also want to include the more fancy multi-group SEM (or MG-CFA) approach, but I have not mastered the lavaan syntax for that yet.

The idea is especially based on this recent article:
Frisby, C. L., & Beaujean, A. A. (2015). Testing Spearman's hypotheses using a bi-factor model with WAIS-IV/WMS-IV standardization data. Intelligence, 51, 79-97.

Let me know if you have any thoughts! :)

**Comment by SachaEpskamp** [comment]
Hi Deletex,

The following code creates a plot with visible edges:

``` r
library("lavaan")
library("semPlot")

mod <- '
g =~ I1 + I2 + I3 + I4 + I5 + I6 + I7 + I8 + I9
F1 =~ I1 + I2 + I3
F2 =~ I4 + I5 + I6
F3 =~ I7 + I8 + I9
'

dat <- simulateData(mod)
fit <- cfa(mod, dat, orthogonal=TRUE)

semPaths(fit, "model", "std", bifactor = "g", layout = "tree2", residuals = FALSE, exoCov = FALSE)
```

![image](https://cloud.githubusercontent.com/assets/1207242/9573899/e4d8d902-4ff3-11e5-955d-d4f41a7e8062.png)

Then the following uses your layout specification:

``` r

m = matrix(nrow = 3, ncol = 9)
m[1, ] = c(0, 11, 0, 0, 12, 0, 0, 13, 0)
m[2, ] = 1:9
m[3, ] = c(rep(0, 4), 10, rep(0, 4))
m

semPaths(fit, "model", "std",layout = m, residuals = FALSE, exoCov = FALSE)
```

![image](https://cloud.githubusercontent.com/assets/1207242/9573930/1d22874a-4ff4-11e5-8952-50afae616601.png)

Both do not produce the invisible edge.. Is this the same for you using these codes?

**Comment by Deleetdk** [comment]
Thanks for the answer. I used your syntax to generate this:

![bifactor_auto](https://cloud.githubusercontent.com/assets/6759913/9574081/d927f018-4f88-11e5-8114-f549c3abbb1d.png)

```
semPaths(fit, "model", "std", bifactor = "g", layout = "tree2", residuals = F, exoCov = F)
```

Using my simulated data.

I removed the bifactor=T, and then it works for generating a hierarchical plot as well. Very nice!

![hier_auto](https://cloud.githubusercontent.com/assets/6759913/9574125/53d9b7b0-4f89-11e5-8fa0-88049a49a6dc.png)

Another question: Your plots have the first variable with a dashed line, but mine doesn't. Is there some reason for that?

**Comment by SachaEpskamp** [comment]
Thanks! please see http://www.tandfonline.com/doi/abs/10.1080/10705511.2014.937847#.VeQIotOqqko for an explanation of the layout methods. The package mostly works for hierarchical models (especially with tree2 and tree3 layouts for many levels) and with a minimal structure between some exogenous and endogenous variables. 

The dashed line indicates fixed parameter estimates, you can change that with the fixedStyle argument.

**Comment by Deleetdk** [comment]
Another question. The above works great as long as there are no cross loadings. However, look what happens if we specify just a single cross loading.

![bi_cross](https://cloud.githubusercontent.com/assets/6759913/9575806/19a996c8-4f98-11e5-9a87-3b2e998cb013.png)
![hier_cross](https://cloud.githubusercontent.com/assets/6759913/9575807/1a61bdac-4f98-11e5-9174-3b22ffeb9dfd.png)

The labels are on top of each other in the bi-factor plot, though hierarchical is fine in this simple case. Now, you told me to try:

> edge.label.position
> Vetor of numbers between 0 and 1 controlling the relative position of each edge label. Defaults to 0.5 for placing edge labels at the middle of the edge.

(Typo in the first word.)

This however would need to be manually changed. So one could perhaps identify indicators with cross loadings and then set their edge.label.position to something else to try to avoid the problem. Is that the best solution?

It can get worse depending on the cross loadings, e.g.:

![cross_bi](https://cloud.githubusercontent.com/assets/6759913/9575914/f531b3ce-4f98-11e5-8f02-c898612829d5.png)
![hier_cross_2](https://cloud.githubusercontent.com/assets/6759913/9575903/d862be5a-4f98-11e5-905d-4b1324ea8b03.png)
(These are made using my Shiny app.)

Good ideas for automatic solutions?

The perfect solution is to have some way of detecting overlapping text in figures, perhaps using an internal representation. Since ggplot2 has the same problems (see http://stackoverflow.com/questions/30598347/how-to-deal-with-ggplot2-and-overlapping-labels-on-a-discrete-axis), it may be very difficult to solve.

**Comment by KarlFetter** [comment]
is the bifactor flag discontinued as of 9/14/17? The setting bifactor='g' doesn't appear to have any effect on my plot, the labels are still overlapping. I'd like to have non-overlapping edge labels and larger node labels. Can any one suggest a fix? thx!

Here's my command:

`semPaths(fit.latent, 'Estimate', 'Estimate', layout='tree3', nodeLabels=c("Q","DIS","SD","PL","PO","Geno"), edge.label.cex=1.75, fade=FALSE, sizeMan=8, bifactor="g")`

![image](https://user-images.githubusercontent.com/22380559/30438653-bf7c5d36-993f-11e7-8adf-bc6a7e724b04.png)

**Comment by tdienlin** [comment]
> Another question. The above works great as long as there are no cross loadings. However, look what happens if we specify just a single cross loading.
> 
> ![bi_cross](https://cloud.githubusercontent.com/assets/6759913/9575806/19a996c8-4f98-11e5-9a87-3b2e998cb013.png)
> ![hier_cross](https://cloud.githubusercontent.com/assets/6759913/9575807/1a61bdac-4f98-11e5-9174-3b22ffeb9dfd.png)

Am currently facing the exact same problem (i.e., visualizing a bifactor model with cross loadings). I reckon we'd need something like [ggrepel](https://github.com/slowkow/ggrepel), which disentangles labels, for semPath? Or any other ideas/solutions?

**Comment by tdienlin** [comment]
The problem can be solved using a workaround: By manually setting the order of the manifest variables (reorder = FALSE), it is possible to have labels not overlap (at least it was possible in my case).

**Comment by phliulei** [comment]
Hi, everyone, how to hide the node of "g"?
