### ISSUE TITLE
lisrelModel no longer available

### ISSUE THREAD

**Issue by AuroreRoland** [SachaEpskamp/semPlot#41]
Hello,
I have estimated a latent network model using the package lnm. Then I wanted to plot it using semPaths. For this, I first have to transform my input since the object type is not right, but the lisrelModel package is no longer available. I have tried several ways to get access to it but nothing seems to be working. Is there another way to transform my input so that I can plot it with semPaths?

Kind regards,
Aurore

**Comment by SachaEpskamp** [comment]
Hi! The `lisrelModel` function is available in the `semPlot` package:

```
library(semPlot)
?lisrelModel
```
