### ISSUE TITLE
Standardized values differing in MPlus Multi-Level-Model

### ISSUE THREAD

**Issue by sammerk** [SachaEpskamp/semPlot#6]
Hey Sascha,

if I plot a Multi-Level-Model from a `.out`file (MPlus) and use the option `what = "std"` the plotted results differ from the stdyx-section in the `.out` file.

Cheers
Samuel

**Comment by SachaEpskamp** [comment]
Oops late reply... But this should be fixed now! Try using the argument modelOpts = list(mplusStd = "stdyx") for this.
