### ISSUE TITLE
Weird lines when plotting WLSMV models

### ISSUE THREAD

**Issue by joaovissoci** [SachaEpskamp/semPlot#8]
Hey Sacha, I love this package and use it all the time. I was plotting some standard psychometric study with CFA on a polytomous scale. I am using lavaan and WLSMV but when I plot with semPaths it returns me a diagram with some weird lines in the observed variables:

![screen shot 2016-11-23 at 14 23 58](https://cloud.githubusercontent.com/assets/1192533/20575723/7e420266-b188-11e6-8e1b-485619834e81.png)

Have you seen this before? My script is:

```
cfa_model <- '
Adt =~  h1 + h2 + h3 + h4 + h5 + h6 + h7 + h8 + h9 + h10
			 '
fit <- lavaan::cfa(cfa_model,
				   data = data,
				   estimator="WLSMV",
				   ordered=names(data))

semPlot::semPaths(fit,"model")
```

**Comment by SachaEpskamp** [comment]
Apologies for the late reply. The lines indicate the thresholds of the variables. You can remove them with thresholds = FALSE
